services:
  auth-service:
    build: .
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth-db
      SPRING_DATASOURCE_USERNAME: auth-user
      SPRING_DATASOURCE_PASSWORD: auth-pass
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - backend

  postgres:
    image: postgres:15.2-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: auth-user
      POSTGRES_PASSWORD: auth-pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: